update apt cache on GitHub Actions
fixes

```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/u/unbound/libunbound2_1.6.7-1ubuntu2.3_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
Fetched 4391 kB in 0s (9409 kB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```