RED-2487: Use `course_key` in `get_site_config_for_event` for Segment events
This an attempt to fixe the error below:

```
Error retrieving Site SEGMENT_KEY. Cannot send event edx.librarycontentblock.content.assigned to Site's Segment account. Sending only to main Segment client. Error was:
Traceback (most recent call last):
  File "lms/djangoapps/grades/course_grade_factory.py", line 54, in read
    return self._read(user, course_data)
  File "lms/djangoapps/grades/course_grade_factory.py", line 155, in _read
    raise PersistentCourseGrade.DoesNotExist
lms.djangoapps.grades.models.PersistentCourseGrade.DoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "common/djangoapps/track/shim.py", line 149, in _get_site_segment_key
    siteconfig = utils.get_site_config_for_event(event_props)
  File "openedx/core/djangoapps/appsembler/eventtracking/utils.py", line 63, in get_site_config_for_event
    "There isn't and org or course_id attribute set in the "
openedx.core.djangoapps.appsembler.eventtracking.exceptions.EventProcessingError: There isn't and org or course_id attribute set in the segment event, so we couldn't determine the site.
```