Cherry pick all of PR #14396 and #14403: Use pip 9.0.1 and setuptools 34.0.2
Fix two wrong egg names

These are the only two egg names that are wrong in this file.  We have
to uninstall i18n-tools, because the distribution name changed.  The
lti-consumer XBlock hasn't changed named, we just had the wrong name in
the requirements file.

(cherry picked from commit 91a235a96d3a91b9a62cf134f1722978eded19bd)

Add versions to all non-dash-e installations

(cherry picked from commit a117416ed2bbd80e5d63d0312fb564be989917eb)

Try the latest of pip and setuptools

(cherry picked from commit 041fede3340ac569b531d0d8cec1308734616e53)

Use latest pyparsing 2.0.x to avoid setuptools entanglement

With 2.0.1, and setuptools 34.0.2, errors happen like:

File "/edx/app/edxapp/venvs/edxapp-sandbox/local/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

(cherry picked from commit 73519b3547359a0b791e39d4665f51ac66449a17)
(cherry picked from commit 8d791b5823acce6a6311ceefe2ec6914f0d33d86)

Keep the sandbox reqs in sync

(cherry picked from commit 84b25dd8969a03665b294fde6be008d3ce1f5f57)

Pyparsing might need to be in pre?

(cherry picked from commit 4433edd05ca7493f98e77c0421fb8f7b81e43d42)

edx-i18n-tools is on PyPI, get it from there.

(cherry picked from commit 7f4ce79ca4fa815fdca77a313796c2d58a01dd94)