RED-2263 fix RecursionError for xblock translations
This exception below is raised because there's an attempt to make the ModuleI18nService
fallback to itself due to the use of the magical
`ModuleI18nService.__getattr__` which returns
`django.utils.translation._fallback` when asked for
`ModuleI18nService._fallback`

This creates a infinite recursion that needs to break.

```
File "xblockutils/templatetags/i18n.py", line 41, in merge_translation
    translation.merge(i18n_service)
...
File "python3.5/gettext.py", line 169, in add_fallback
    self._fallback.add_fallback(fallback)
RecursionError: maximum recursion depth exceeded"
```