Handle segment exceptions more gracefully
When an error happens in segment, Tahoe handle it incorrectly and throws
another exception:

```
Unable to send event to backend: segment
...
openedx.core.djangoapps.appsembler.eventtracking.exceptions.EventProcessingError: There isn't and org or course_id attribute set in the segment event, so we couldn't determine the site.
...
During handling of the above exception, another exception occurred:
AttributeError: 'EventProcessingError' object has no attribute 'msg'"
```

The solution is to use Python's native `exc_info=True` to log the
exception correctly.

Another fix is needed to fix the original EventProcessingError error.