BOM-1756 Fixing AttributeError: module 'cgi' has no attribute 'escape'.
https://docs.python.org/3/whatsnew/3.8.html
escape are removed from the cgi module