feat: Also set `MPLCONFIGDIR` to make matplotlib complain less
Example output from running `import matplotlib; 1/0`, without the change:

```
Matplotlib created a temporary cache directory at /tmp/codejail-hveq16ah/tmp/matplotlib-tv0c_vzt because the default path (/home/sandbox/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "jailed_code", line 19, in <module>
    exec(code, g_dict)
  File "<string>", line 1, in <module>
ZeroDivisionError: division by zero
```

With the fix:

```
Traceback (most recent call last):
  File "jailed_code", line 19, in <module>
    exec(code, g_dict)
  File "<string>", line 1, in <module>
ZeroDivisionError: division by zero
```