Update Django Extensions version from 1.5.9 to 3.1.0
Django Extensions 1.5.9 breaks on at least some functionality in Django
2.2. Specifically when you run `./manage.py cms show_urls`, you get:

```
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django_extensions/management/commands/show_urls.py", line 9, in <module>
    from django.core.urlresolvers import RegexURLPattern, RegexURLResolver, LocaleRegexURLResolver
ImportError: No module named 'django.core.urlresolvers'
```

This PR upgrades to the latest version that supports Python 3.5