temp: remove flaky rate limiting test.py
The test LoginAndRegistrationTest.test_login_and_registration_form_ratelimited was found to be flaky, so it is being removed.

Error details:
>       assert response.status_code == 429
E       assert 200 == 429
openedx/core/djangoapps/user_authn/views/tests/test_logistration.py:132: AssertionError