Revert "instrument lms.djangoapps.courseware.module_render functions"
This reverts commit f91b2139aac38681d06240fe36b7c7e47a69443f.

I'm reverting the instruments because I think it's causing a bug RED-2188

Decorators are hard to debug and sometimes interfere with the code:

**Related exception:**

```
"Internal Server Error: /courses/course-v1:******/courseware/******/******/" \
"Error in /courses/course-v1:******/courseware/******/******/: user=******, effective_user=******, course=course-v1:******
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/views/index.py", line 171, in get
    return self.render(request)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/beeline/trace.py", line 375, in inner
    return fn(*args, **kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/views/index.py", line 275, in render
    return render_to_response('courseware/courseware.html', self._create_courseware_context(request))
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/beeline/trace.py", line 375, in inner
    return fn(*args, **kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/views/index.py", line 495, in _create_courseware_context
    table_of_contents['chapters'],
TypeError: tuple indices must be integers or slices, not str"
```